export * from "./i18n";
export { AppShell } from "./AppShell";
// Re-exported so the app depends on one UI package for translation hooks.
export { I18nextProvider, useTranslation } from "react-i18next";
export type { i18n as I18n } from "i18next";
export { describeProviderError } from "./errors/provider-error-messages";
export type { ProviderErrorAction, ProviderErrorDescription } from "./errors/provider-error-messages";
export { Onboarding } from "./onboarding/Onboarding";
export type { OnboardingDraft, OnboardingProps } from "./onboarding/Onboarding";
export { addInterest, removeInterest } from "./onboarding/interests";
export { KeyEntry } from "./key/KeyEntry";
export type { KeyEntryProps } from "./key/KeyEntry";
export { ConversationList } from "./conversations/ConversationList";
export type { ConversationListProps } from "./conversations/ConversationList";
export { ChatView } from "./chat/ChatView";
export type { ChatViewProps } from "./chat/ChatView";
export { MessageBubble } from "./chat/MessageBubble";
export type { ChatMessage, MessageBubbleProps } from "./chat/MessageBubble";
export { Composer } from "./chat/Composer";
export type { ComposerProps } from "./chat/Composer";
export { SafeBlockRenderer } from "./chat/SafeBlockRenderer";
